from datetime import datetime, timezone

from weasyprint import HTML


REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<style>
    body {{ font-family: 'Helvetica', 'Arial', sans-serif; margin: 40px; color: #333; }}
    h1 {{ color: #1a1a2e; border-bottom: 3px solid #e94560; padding-bottom: 10px; }}
    h2 {{ color: #1a1a2e; margin-top: 30px; }}
    .grade {{ font-size: 72px; font-weight: bold; text-align: center; padding: 20px;
              border-radius: 12px; margin: 20px auto; width: 120px; }}
    .grade-A {{ background: #10b981; color: white; }}
    .grade-B {{ background: #3b82f6; color: white; }}
    .grade-C {{ background: #f59e0b; color: white; }}
    .grade-D {{ background: #f97316; color: white; }}
    .grade-F {{ background: #ef4444; color: white; }}
    .score {{ text-align: center; font-size: 24px; color: #666; }}
    .summary {{ background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }}
    .summary-grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; }}
    .summary-item {{ text-align: center; padding: 10px; border-radius: 6px; }}
    .critical {{ background: #fef2f2; color: #dc2626; }}
    .high {{ background: #fff7ed; color: #ea580c; }}
    .medium {{ background: #fefce8; color: #ca8a04; }}
    .low {{ background: #eff6ff; color: #2563eb; }}
    table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
    th {{ background: #1a1a2e; color: white; padding: 12px; text-align: left; }}
    td {{ padding: 10px; border-bottom: 1px solid #eee; }}
    tr:nth-child(even) {{ background: #f8f9fa; }}
    .severity-badge {{ padding: 3px 8px; border-radius: 4px; font-size: 12px;
                       font-weight: bold; text-transform: uppercase; }}
    .evidence {{ background: #f1f5f9; padding: 10px; border-radius: 4px;
                 font-family: monospace; font-size: 12px; white-space: pre-wrap;
                 word-break: break-all; margin: 5px 0; }}
    .dismissed td {{ opacity: 0.5; }}
    .dismiss-label {{ font-size: 11px; color: #666; font-style: italic; }}
    .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd;
               color: #999; font-size: 12px; }}
</style>
</head>
<body>
    <h1>MCP Security Scan Report</h1>
    <p>Generated: {generated_at}</p>

    <div class="grade grade-{grade}">{grade}</div>
    <div class="score">Score: {score}/100</div>

    <div class="summary">
        <h2>Summary</h2>
        <div class="summary-grid">
            <div class="summary-item critical">Critical: {critical_count}</div>
            <div class="summary-item high">High: {high_count}</div>
            <div class="summary-item medium">Medium: {medium_count}</div>
            <div class="summary-item low">Low: {low_count}</div>
        </div>
        <p>Total findings: {total_findings}</p>
    </div>

    <h2>Findings</h2>
    {findings_html}

    <div class="footer">
        <p>Generated by MCP Security Scanner v0.1.0</p>
    </div>
</body>
</html>
"""

FINDING_ROW = """
<tr{row_class}>
    <td><span class="severity-badge {severity}">{severity_upper}</span></td>
    <td><strong>{title}</strong><br><small>{checker} | {location}{source_info}</small>{dismiss_label}</td>
    <td>{description}</td>
    <td>{remediation}</td>
</tr>
"""


class PDFReportGenerator:
    def generate(self, scan_data: dict) -> bytes:
        summary = scan_data.get("summary", {})
        by_severity = summary.get("by_severity", {})

        findings_rows = []
        dismissed_count = 0
        for f in scan_data.get("findings", []):
            if isinstance(f, dict):
                sev = str(f.get("severity", ""))
                title = f.get("title", "")
                checker = f.get("checker", "")
                location = f.get("location", "")
                description = f.get("description", "")
                remediation = f.get("remediation", "")
                source_file = f.get("source_file")
                source_line = f.get("source_line")
                dismissed_as = f.get("dismissed_as")
                dismissed_reason = f.get("dismissed_reason")
            else:
                sev = f.severity.value if hasattr(f.severity, "value") else str(f.severity)
                title = f.title
                checker = f.checker
                location = f.location
                description = f.description
                remediation = f.remediation
                source_file = getattr(f, "source_file", None)
                source_line = getattr(f, "source_line", None)
                dismissed_as = getattr(f, "dismissed_as", None)
                dismissed_reason = getattr(f, "dismissed_reason", None)
            source_info = ""
            if source_file:
                source_info = f" | {source_file}" + (f":{source_line}" if source_line else "")
            row_class = ""
            dismiss_label = ""
            if dismissed_as:
                dismissed_count += 1
                row_class = ' class="dismissed"'
                label_text = dismissed_as.replace("_", " ").title()
                if dismissed_reason:
                    label_text += f" — {dismissed_reason}"
                dismiss_label = f'<br><span class="dismiss-label">[{self._escape(label_text)}]</span>'
            findings_rows.append(
                FINDING_ROW.format(
                    severity=sev,
                    severity_upper=sev.upper(),
                    title=self._escape(title),
                    checker=self._escape(checker),
                    location=self._escape(location),
                    source_info=self._escape(source_info),
                    description=self._escape(description),
                    remediation=self._escape(remediation),
                    row_class=row_class,
                    dismiss_label=dismiss_label,
                )
            )

        if findings_rows:
            findings_html = (
                "<table><tr><th>Severity</th><th>Finding</th>"
                "<th>Description</th><th>Remediation</th></tr>"
                + "".join(findings_rows)
                + "</table>"
            )
        else:
            findings_html = (
                "<p>No findings detected. The scanned MCP configuration appears clean.</p>"
            )

        html_content = REPORT_TEMPLATE.format(
            generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            grade=scan_data.get("grade", "?"),
            score=scan_data.get("score", 0),
            critical_count=by_severity.get("critical", 0),
            high_count=by_severity.get("high", 0),
            medium_count=by_severity.get("medium", 0),
            low_count=by_severity.get("low", 0),
            total_findings=self._format_total(summary.get("total", 0), dismissed_count),
            findings_html=findings_html,
        )

        pdf_bytes = HTML(string=html_content).write_pdf()
        return pdf_bytes

    def _format_total(self, active: int, dismissed: int) -> str:
        if dismissed > 0:
            return f"{active} active findings ({dismissed} dismissed)"
        return str(active)

    def _escape(self, text: str) -> str:
        return (
            str(text)
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
        )
